### PR TITLE
Make MDC loging safe in the presence of cancelation

### LINKED ISSUE #274: MDC is not cleared on task cancellation
In the case where the logging task (with a context for MDC) gets cancelled, the MDC context is not cleared/restored to it's previous state.

Here is an [example code](https://github.com/ikempf/log4cats-mdc-clear/blob/master/src/main/scala/com/ikempf/Start.scala) that quickly produces the issue. A log setting the MDC context gets cancelled. Other log tasks then randomly display keys from the "leaked" MDC context. 

I've had a look at the [MDC related code](https://github.com/ChristopherDavenport/log4cats/blob/master/slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/Slf4jLoggerInternal.scala). I was about to suggest using a `Resource` or a `Bracket` to clear/restore the MDC to it's previous state but that's already the case.
I'm not sure why this is not working as expected 🤔, I'll have another look this weekend.

### PR DESCRIPTION
**Pull request by kubukoz**
Closes #274

### CODE REVIEW

**Comment by kubukoz** [comment]
I think I'll redo it without SyncIO...

**Comment by kubukoz** [comment]
I'll think of a test, shouldn't be too hard...

**Comment by kubukoz** [comment]
Okay, I added a test that ensures that the cancelation runs on a different thread (while we're logging) and that both threads get the correct MDC context after the whole thing. The old version fails the test.

**Comment by kubukoz** [comment]
All good on my side :)

**Comment by kubukoz** [comment]
@ChristopherDavenport would you mind releasing? I'd like to depend on this behavior :)

**Comment by ChristopherDavenport** [comment]
https://travis-ci.org/github/ChristopherDavenport/log4cats/builds/685830390 - I may need to transition onto github actions which I haven'tn done yet

**Comment by kubukoz** [comment]
I'm getting that error on master too, will submit a fix :)

**Comment by kubukoz** [comment]
https://github.com/ChristopherDavenport/log4cats/pull/313

**Pull request merged**
